"""Estructura inicial limpia

Revision ID: faa585b2e6c7
Revises: 
Create Date: 2026-02-20 10:23:49.666889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa585b2e6c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('rut', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('rut')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metodo_pago', sa.Enum('contado', 'credito automotriz', 'T. crédito', 'T. débito', name='metodo_pago_enum'), nullable=False),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('vehiculos',
    sa.Column('patente', sa.String(length=8), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('chasis_n', sa.String(length=100), nullable=False),
    sa.Column('motor_n', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('propietario_rut', sa.String(length=10), nullable=True),
    sa.Column('kilometraje', sa.Integer(), nullable=True),
    sa.Column('precio_acordado', sa.Integer(), nullable=True),
    sa.Column('tipo_adquisicion', sa.String(length=50), nullable=False),
    sa.Column('costo_compra', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['propietario_rut'], ['clientes.rut'], ),
    sa.PrimaryKeyConstraint('patente'),
    sa.UniqueConstraint('chasis_n'),
    sa.UniqueConstraint('motor_n')
    )
    op.create_table('notas_de_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_rut', sa.String(length=10), nullable=False),
    sa.Column('vehiculo_patente', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.Column('fecha_venta', sa.Date(), nullable=False),
    sa.Column('monto_final', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('completada', 'pendiente', 'anulada', 'reservada', name='estado_venta_enum'), nullable=False),
    sa.Column('monto_reserva', sa.Integer(), nullable=True),
    sa.Column('dias_vigencia', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_rut'], ['clientes.rut'], ),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_patente'], ['vehiculos.patente'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pago_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notas_de_venta')
    op.drop_table('vehiculos')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('pagos')
    op.drop_table('clientes')
    # ### end Alembic commands ###
